### ISSUE TITLE
react/docs/reconciliation - Motivation中的翻译错误

### ISSUE THREAD

**Issue by Leona-Jly** [discountry/react#118]
在 https://facebook.github.io/react/docs/reconciliation.html 中，Motivation目的这块的第一段最后一行 "React then needs to figure out how to efficiently update the UI to match the most recent tree." 被翻译为 "React需要算出如何高效更新UI以匹配最为接近的树。"。
"the most recent tree" 应该被翻译为"最新(或最后被修改)的树"，即翻译应该为 "React需要算出如何高效更新UI以匹配最新的树。"

**Comment by discountry** [comment]
已修正，感谢
