### ISSUE TITLE
代码缩进引起误解

### ISSUE THREAD

**Issue by OfficialYoungX** [discountry/react#267]
![react_bug](https://user-images.githubusercontent.com/25839518/40838423-a5cba488-65d0-11e8-9822-3900facaaed9.jpg)

This is not a bug, but I think in some situation this will make the beginners doubting.

The indentation of the code is no right.

check [this](https://doc.react-china.org/docs/rendering-elements.html#更新元素渲染) page.

**Comment by discountry** [comment]
fixed.

**Comment by NevenLeung** [comment]
The indent of the first line code in almost every code block is still there. 

The markdown file seems to be fine, but somehow it doesn't display well in the rendering result.

 Please check the docs and do something for it.
