### ISSUE TITLE
React 中文官网BUG！！！

### ISSUE THREAD

**Issue by ablikim915** [discountry/react#333]
从昨天下午开始出现了这个问题

![image](https://user-images.githubusercontent.com/15664144/51593065-2289f780-1f2c-11e9-8353-b572a67f867f.png)

当点击展开那个区域的时候交互失效，展开不了。还有，跳转其他页面的时候路由有变化，但是页面加载特别慢，手动刷新后秒加载。
url: https://react.docschina.org/docs/thinking-in-react.html

**Comment by Kavelaa** [comment]
对，希望能修复下，备用网站工作正常。

**Comment by discountry** [comment]
fixed
